openapi: 3.0.0
info:
  title: CFCB Complaint Outcome Predictor
  description: Outcome predictor for submitted complaints to the Consumer Financial
    Complaint Bureau
  contact:
    email: alex.retana@live.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
- url: https://api.example.com/v1/users
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /retrain_model:
    post:
      tags:
      - admins
      summary: Retrains model
      description: Runs python script to retain model
      operationId: addInventory
      responses:
        "201":
          description: model retrained
        "400":
          description: invalid input
  /prediction/{complaintId}:
    get:
      tags:
      - developers
      summary: Predicts Complaint Outcome
      description: Predict the Outcome of Complaint by Specifying Complaint ID
      operationId: predict
      parameters:
      - name: complaintId
        in: path
        description: Specify Complaint ID for prediction
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 3398126
      responses:
        "200":
          description: Complaint processed, returning results of prediction in the
            form of {complaintID, Predicted Outcome, and probility of "Closed with
            relief"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Call unsuccessful
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        complaintID:
          type: integer
          example: 3398126
        pred:
          type: string
          example: Closed without relief
        proba:
          type: number
          example: 39.31
